#!/usr/bin/env python3
import glob
import os
import sys

import defusedxml.ElementTree as ET


def collect_pmd_violations():
    violations = []
    for f in sorted(glob.glob("**/target/pmd.xml", recursive=True)):
        tree = ET.parse(f)
        root = tree.getroot()
        ns = {"pmd": "http://pmd.sourceforge.net/report/2.0.0"}
        for file_el in root.findall("pmd:file", ns):
            path = os.path.relpath(file_el.get("name"))
            for v in file_el.findall("pmd:violation", ns):
                violations.append(
                    {
                        "file": path,
                        "line": v.get("beginline"),
                        "rule": v.get("rule"),
                        "priority": v.get("priority"),
                        "url": v.get("externalInfoUrl", ""),
                        "message": v.text.strip() if v.text else "",
                    }
                )
    return violations


def collect_spotbugs_findings():
    bugs = []
    for sb_file in sorted(glob.glob("**/target/spotbugsXml.xml", recursive=True)):
        module_dir = os.path.dirname(os.path.dirname(sb_file))
        tree = ET.parse(sb_file)
        root = tree.getroot()
        for bug in root.findall(".//BugInstance"):
            source = bug.find('.//SourceLine[@primary="true"]')
            if source is None:
                source = bug.find(".//SourceLine")
            long_msg = bug.find("LongMessage")
            sourcepath = source.get("sourcepath", "") if source is not None else ""
            start = source.get("start", "") if source is not None else ""
            full_path = sourcepath
            if sourcepath and module_dir:
                candidate = os.path.join(module_dir, "src/main/java", sourcepath)
                if os.path.exists(candidate):
                    full_path = candidate
                else:
                    candidate = os.path.join(module_dir, "src/test/java", sourcepath)
                    if os.path.exists(candidate):
                        full_path = candidate
            bugs.append(
                {
                    "file": full_path,
                    "line": start,
                    "type": bug.get("type", ""),
                    "category": bug.get("category", ""),
                    "priority": bug.get("priority", ""),
                    "message": long_msg.text if long_msg is not None else "",
                }
            )
    return bugs


def build_report(pmd_violations, sb_bugs):
    lines = ["<!-- static-analysis-report -->", "## Static Analysis Report", ""]

    if pmd_violations:
        n = len(pmd_violations)
        lines.append(f'### PMD ({n} violation{"s" if n != 1 else ""})')
        lines.append("")
        lines.append("| File | Line | Rule | Priority | Description |")
        lines.append("|------|------|------|----------|-------------|")
        for v in pmd_violations:
            rule = f'[{v["rule"]}]({v["url"]})' if v["url"] else v["rule"]
            lines.append(
                f'| `{v["file"]}` | {v["line"]} | {rule} | {v["priority"]} | {v["message"]} |'
            )
        lines.append("")

    if sb_bugs:
        n = len(sb_bugs)
        lines.append(f'### SpotBugs ({n} finding{"s" if n != 1 else ""})')
        lines.append("")
        lines.append("| File | Line | Type | Category | Priority | Description |")
        lines.append("|------|------|------|----------|----------|-------------|")
        for b in sb_bugs:
            lines.append(
                f'| `{b["file"]}` | {b["line"]} | {b["type"]} | {b["category"]} | {b["priority"]} | {b["message"]} |'
            )
        lines.append("")

    lines.append("---")
    lines.append(
        "*Generated by the static analysis workflow. Fix the violations and push to update this report.*"
    )
    return "\n".join(lines)


def main():
    pmd_violations = collect_pmd_violations()
    sb_bugs = collect_spotbugs_findings()

    if not pmd_violations and not sb_bugs:
        print("No findings to report.")
        sys.exit(0)

    report = build_report(pmd_violations, sb_bugs)

    with open("static-analysis-report.md", "w") as f:
        f.write(report)

    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with open(summary, "a") as f:
            f.write(report)

    print(
        f"Report generated: {len(pmd_violations)} PMD violation(s), {len(sb_bugs)} SpotBugs finding(s)"
    )


if __name__ == "__main__":
    main()
